FROM alpine:latest

RUN apk add --no-cache \
    build-base \
    cmake \
    git \
    bash \
    musl-dev \
    linux-headers \
    aarch64-linux-musl-gcc \
    aarch64-linux-musl-binutils

WORKDIR /app